apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- pvc.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: grafana
    namespace: infra-monitoring
  patch: |-
    - op: add
      path: /spec/template/spec/volumes/-
      value:  
        name: storage
        persistentVolumeClaim:
          claimName: grafana-pvc
- target:
    group: apps
    version: v1
    kind: Deployment
    name: grafana
    namespace: infra-monitoring
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: storage
        mountPath: "/var/lib/grafana"