apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana.yaml
configMapGenerator:
- name: grafana
  namespace: infra-monitoring
  files:
  - config/datasources.yaml
  - config/grafana.ini