apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# NOTE: Patching ConfigMap data is not supported. Following will not work
# patches:
# - target:
#     group: ""
#     version: v1
#     kind: ConfigMap
#     name: grafana
#     namespace: infra-monitoring
#   patch: |-
#     - op: add
#       path: /data/datasources.yaml/datasources/-
#       value:
#         access: proxy
#         jsonData:
#           maxLines: 1000
#         name: Loki
#         type: loki
#         url: http://loki:3100

# This will merge configmaps if one already exist. 
# But anything under the map array 'data' will be replaced
configMapGenerator:
- name: grafana
  namespace: infra-monitoring
  behavior: merge
  files:
  - datasources.yaml