apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: ""
    version: v1
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
  patch: |-
    - op: add
      path: /spec/type
      value: "NodePort"
    - op: add
      path: /spec/ports/0/nodePort
      value: 31080
    - op: add
      path: /spec/ports/1/nodePort
      value: 31443

