apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: nginx-ingress-controller
    namespace: ingress-nginx
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--https-port=8443"
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--validating-webhook-certificate=/usr/local/certificates/tls.crt"
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--validating-webhook-key=/usr/local/certificates/tls.key"
