apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: ""
    version: v1
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
  patch: |-
    - op: replace
      path: /spec/type
      value: "LoadBalancer"
