apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: loki
    namespace: loki
    releaseName: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.32.0
    includeCRDs: true
    valuesInline:
      minio:
        enabled: true
