apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- ./secret.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--default-ssl-certificate=$(POD_NAMESPACE)/default-ssl-certificate"